---

    - name: install snmp package
      yum:
        name: net-snmp
        state: present

    - name: insert distro shell script
      copy:
        backup: true
        force: no
        mode: '0755'
        owner: 'root'
        group: 'root'
        src: distro
        dest: /usr/bin/distro

    - name: create override directory for snmpd
      file:
        path: /etc/systemd/system/snmpd.service.d
        mode: '0755'
        owner: 'root'
        group: 'root'
        state: directory

    - name: insert systemd override for snmpd
      copy:
        backup: false
        force: no
        mode: '0644'
        owner: 'root'
        group: 'root'
        src: override.conf
        dest: /etc/systemd/system/snmpd.service.d/override.conf

    - name: reload systemd config
      delegate_to: "{{ guest_ip_addr }}"
      systemd: daemon_reload=yes

    - name: insert snmpd configuration file
      copy:
        backup: true
        force: yes
        mode: '0600'
        owner: 'root'
        group: 'root'
        src: snmpd.conf
        dest: /etc/snmp/snmpd.conf

    - name: restart snmpd
      delegate_to: "{{ guest_ip_addr }}"
      service: name=snmpd enabled=true state=restarted

